return {}

-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         pyright = {
--           -- Disable pyright
--           enabled = false,
--           -- Prevent pyright install from mason
--           mason = false,
--           -- handlers = {
--           --   -- Disable pyright diagnostics
--           --   ["textDocument/publishDiagnostics"] = function() end,
--           -- },
--         },
--       },
--     },
--   },
-- }

-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         ruff = {
--           handlers = {
--             ["textDocument/publishDiagnostics"] = function() end,
--           },
--           -- Prevent ruff install from mason
--           mason = false,
--         },
--       },
--     },
--   },
-- }
